servers:
  rabbitmq-1:
    host: 10.100.200.6
    port: 5672
    username: rabbit
    password: 1sd12fcxf34k
  rabbitmq-2:
    host: 10.100.200.7
    port: 5672
    username: rabbit
    password: 1sd12fcxf34k
  rabbitmq-3:
    host: 185.104.107.29
    port: 5672
    username: farit
    password: sH0hF2qD6ebF